### PR TITLE
fixed tests

### PR DESCRIPTION
**Pull request by denen99**
@joprice you left broken tests :-)

This should fix, all tests pass now.

### CODE REVIEW

**Comment by joprice** [comment]
Ooops! Apropos to that, could you enable to circle integration so we start getting builds on our prs?

**Comment by denen99** [comment]
I added CircleCI, but its not building this branch, do i need to do anything specific to get it to build non-master branch ?

**Comment by denen99** [comment]
Nevermind, created the PR before the integration.

**Comment by denen99** [comment]
Tests passed , merge it !

**Pull request merged**
